### ISSUE TITLE
jQuery Zoom only works on first thumbnail

### ISSUE THREAD

**Issue by kirillzakharov** [Cam/Shopify-Theme-Framework#33]
When a product has multiple thumbnails, the zoom is only being applied to the first featured product. 

See demo:
https://theme-framework.myshopify.com/collections/frontpage/products/demo-product-1

**Comment by Emma-Dolan** [comment]
any update on the fix?

**Comment by Cam** [comment]
Hi @Emma-Dolan. Unfortunately this project isn't being actively updated anymore. You can fix that issue by re-initialising the zoom on image change though. And PRs are definitely welcome!
