### ISSUE TITLE
Reveal Modal not working when trigger button is separate from the modal?

### ISSUE THREAD

**Issue by spring-91** [Cam/Shopify-Theme-Framework#35]
I've tried to implement the Quick View Modal in my store and for some reason if I open the model on the product.liquid page all the content displays inside the modal. However if I open the modal on the index.liquid or the collection.liquid page, empty image and dropdown fields are presented.

The only reason I can think this might not be working is because I have the <a> link trigger in a separate snippet to the actual modal I want to be revealed - this is due to my setup. The thing is I can't understand why this might be? Otherwise I must be completely missing something in my code.

Here's a link to my [test store] (http://test-store-980.myshopify.com). If you click 'Buy' it opens the Quick View modal. 

If this is something you could help with I would be truly grateful!

**Comment by Cam** [comment]
Hi @spring-91. That doesn't look like this framework to me.
