### ISSUE TITLE
Size of product image hover

### ISSUE THREAD

**Issue by ineptian** [Cam/Shopify-Theme-Framework#37]
How can I change the size that shopify is giving to the product images I am uploading so that the rollover zoom functionality works on large screen? Also how can I make it so that if you are selected on an image other than the featured image it chooses the correct image to zoom in on, right now it always shows the featured image.

Example: http://asterisk-2.myshopify.com/collections/protection/products/cyto-cell-knee-protection-system
pw: whaick

**Comment by Cam** [comment]
Hi @ineptian. In the product.liquid (with zoom), in the #product-images, look for the 2 images you have as '_grande'. One of those should be something like '_2048x2048' - see http://cam.vc/lpiruls for sizes.

As for the multi image zoom. You would need to write a bit of javascript for that. The zoom I included is pretty basic. Personally, I would probably just grab something like this http://cam.vc/lpiruls and customise it.

The site is looking great!

**Comment by Cam** [comment]
Here's a free script you need for the multi image zoom :) http://www.dynamicdrive.com/dynamicindex4/featuredzoomer.htm

**Comment by ineptian** [comment]
Hey Cam,

Thanks for the quick response and of course providing this theme! I am going to try and get both of my issues fixed tomorrow morning with your suggested solutions and will let you know the outcome!

Thanks again!
