### ISSUE TITLE
Collection Page Rows

### ISSUE THREAD

**Issue by ineptian** [Cam/Shopify-Theme-Framework#39]
Hey Cam thanks for your help with everything thus far. I am having some trouble controlling how the products are aligning on the collection pages.  I tried to change the css to make a medium size product grid to go along with the large and small, but my changes don't seem to be taking effect.

I want every row to always display three products on large and medium screens, right now at certain sizes my rows get blow out and a product drops down.

Here is a link: http://asterisk-2.myshopify.com/collections/accessories-1
password: whaick

Thanks again.

**Comment by ineptian** [comment]
I found a temporary fix so you cant see it on the shop pages anymore but any insight would be helpful. It looks like an extra p tag is getting added to some of the product descriptions but I'm not sure why. I ended up taking the first opening, and last closing p tag on the products that had this problem and this works as a temporary workaround.

**Comment by Cam** [comment]
Hi @ineptian. I'm not sure I am entirely understanding what the issue you are having is, but if I am getting it right, you could probably set a fixed height for the descriptions in the collection pages on the specific screen sizes.
